# Alpaca API Configuration
# 建议使用环境变量加载，例如 ALPACA_API_KEY
alpaca:
  # 通过环境变量 ALPACA_API_KEY 和 ALPACA_SECRET_KEY 加载
  api_key: null
  secret_key: null
  paper: true  # true for paper trading, false for live trading

# Trading Parameters
trading:
  symbols: ["SPY", "QQQ"]  # 要交易的品种列表
  timeframe: "1Day"      # K线周期 (e.g., 1Min, 5Min, 1Day)
  max_active_trades: 5   # 最多同时持有的仓位数

# Risk Management
risk:
  risk_per_trade: 0.02  # 每笔交易的风险敞口（占总资金的百分比），例如 0.02 代表 2%
  default_stop_loss_atr_multiplier: 2.0 # 默认止损距离（ATR的倍数）

# Logging Configuration
logging:
  level: "INFO"  # 日志级别 (DEBUG, INFO, WARNING, ERROR)
  
