# Alpaca API Configuration
alpaca:
  api_key: null
  secret_key: null
  paper: true

# Data Parameters
data:
  symbols: ["SPY"]
  timeframe: "1Min"
  start_date: "2025-08-25" # Default start date
  end_date: "2025-09-01"   # Default end date

# Backtest Configuration
backtest:
  cash: 10000
  commission: 0.002

# Strategy Configuration
strategy:
  params:
    risk_per_trade: 0.02
    

# Logging Configuration
logging:
  level: "INFO"
