# Alpaca API Configuration
alpaca:
  api_key: null
  secret_key: null
  paper: true

# Data Parameters
data:
  symbols: ["SPY"]
  timeframe: "1Day"
  start_date: "2024-01-01" # Default start date
  end_date: "2024-12-31"   # Default end date

# Backtest Configuration
backtest:
  cash: 10000
  commission: 0.002

# Strategy Configuration
strategy:
  params:
    risk_per_trade: 0.02
    n_bars_for_trend: 10

# Logging Configuration
logging:
  level: "INFO"
